(function(){'use strict';
  var checklist=['Фотографии относятся к берёзе повислой','Листья сняты целиком на светлом фоне','Паспорт дерева и дата заполнены','Координаты соответствуют назначенной территории','Нет повторяющихся фотографий','Контрольные точки проверены'];
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function state(r){if(r.status==='published')return 'Опубликована';if(r.status==='rejected')return 'Отклонена';if(r.status==='needs_revision')return 'Возвращена на исправление';if(r.aiStatus==='checked')return 'ФА рассчитана';if(r.aiStatus==='processing')return 'Идёт расчёт ФА';if(r.humanStatus==='approved'||r.status==='human_approved')return 'Разметка одобрена';return 'Ждёт модератора';}
  document.addEventListener('DOMContentLoaded',async function(){
    var user=await EcoAuth.requireAuthAsync(),list=document.getElementById('moderationList'),denied=document.getElementById('moderationDenied'),deniedText=document.getElementById('moderationDeniedText'),message=document.getElementById('moderationMessage');if(!user||!list)return;
    function note(text,tone){message.textContent=text||'';message.dataset.state=tone||'';message.hidden=!text;}
    if(!['moderator','admin'].includes(user.role)){denied.hidden=false;deniedText.textContent='Этот раздел доступен модератору и администратору.';return;}
    if(user.role==='moderator'){var course;try{course=await EcoAuth.refreshCourseStatus('moderator');}catch(_){course=null;}if(!course||!course.completed){denied.hidden=false;deniedText.textContent='Сначала завершите курс и наберите не менее 9 баллов из 10.';return;}}
    async function load(){try{await EcoAuth.refreshRequests('all');render();}catch(e){note('Не удалось загрузить заявки из Supabase.','error');}}
    function render(){var rows=EcoAuth.getAllRequests();if(!rows.length){list.innerHTML='<p class="zayavki-pusty">Новых заявок пока нет.</p>';return;}list.innerHTML=rows.map(function(r){var checks=checklist.map(function(x,i){return '<label><input type="checkbox" data-check="'+i+'" '+(r.moderationChecklist&&r.moderationChecklist[i]?'checked':'')+'> '+x+'</label>';}).join('');var result=r.aiResult&&r.aiResult.meanFa!=null?'<p class="moderaciya-result"><strong>Средняя ФА:</strong> '+Number(r.aiResult.meanFa).toFixed(4)+'</p>':'';var files=(r.files||[]).slice(0,4).map(function(f,i){return f.url?'<img src="'+esc(f.url)+'" alt="Лист '+(i+1)+'">':'';}).join('');return '<article class="moderaciya-zayavka" data-id="'+esc(r.id)+'"><div class="moderaciya-zayavka__head"><div><p class="sekciya-metka">'+esc(state(r))+'</p><h2>'+esc(r.title||'Точка мониторинга')+'</h2></div><span>'+esc(r.collectionDate||'Дата не указана')+'</span></div><dl><dt>Координаты</dt><dd>'+esc(r.coordinates||'не указаны')+'</dd><dt>Участник</dt><dd>'+esc(r.userName||r.userEmail||'не указан')+'</dd><dt>Листьев</dt><dd>'+Number((r.files||[]).length)+'</dd></dl><div class="moderaciya-preview">'+files+'</div><div class="moderaciya-checklist">'+checks+'</div><label class="pole-podpis">Комментарий<textarea class="pole-vvod" data-comment rows="3">'+esc(r.moderationReason||'')+'</textarea></label>'+result+'<div class="moderaciya-deystviya"><a class="knopka-vtorichnaya" href="review.html?id='+encodeURIComponent(r.id)+'">Проверить точки</a><button class="knopka-vtorichnaya" data-action="needs_revision" type="button">Вернуть</button><button class="knopka-vtorichnaya" data-action="rejected" type="button">Отклонить</button><button class="knopka-osnovnaya" data-action="human_approved" type="button">Одобрить разметку</button>'+(r.humanStatus==='approved'||r.status==='human_approved'?'<button class="knopka-osnovnaya" data-action="analyse" type="button">Рассчитать ФА</button>':'')+(r.aiStatus==='checked'&&r.status!=='published'?'<button class="knopka-osnovnaya" data-action="publish" type="button">Опубликовать</button>':'')+'</div></article>';}).join('');}
    list.addEventListener('change',async function(e){if(!e.target.matches('[data-check]'))return;var card=e.target.closest('[data-id]'),values=Array.from(card.querySelectorAll('[data-check]')).map(function(x){return x.checked;});try{await EcoAuth.saveRequestUpdate(card.dataset.id,{moderationChecklist:values});}catch(_){note('Не удалось сохранить чек-лист.','error');}});
    list.addEventListener('click',async function(e){var b=e.target.closest('[data-action]');if(!b)return;var card=b.closest('[data-id]'),id=card.dataset.id,action=b.dataset.action,comment=card.querySelector('[data-comment]').value.trim();b.disabled=true;try{if(action==='analyse'){await EcoAuth.startRequestAnalysis(id);b.textContent='Расчёт… 10';for(var n=9;n>1;n--){await new Promise(function(resolve){setTimeout(resolve,1000);});b.textContent='Расчёт… '+n;}await EcoAuth.finishRequestAnalysis(id);}else if(action==='publish'){await EcoAuth.publishRequest(id);}else{var checks=Array.from(card.querySelectorAll('[data-check]')).map(function(x){return x.checked;});if(action==='human_approved'&&!checks.every(Boolean))throw new Error('CHECKLIST');if((action==='rejected'||action==='needs_revision')&&!comment)throw new Error('COMMENT');await EcoAuth.saveRequestUpdate(id,{status:action,humanStatus:action==='human_approved'?'approved':action==='rejected'?'rejected':'pending',moderationReason:comment,moderationChecklist:checks});}await load();note('Изменения сохранены.','success');}catch(err){b.disabled=false;note(err.message==='CHECKLIST'?'Перед одобрением отметьте весь чек-лист.':err.message==='COMMENT'?'Напишите, что именно нужно исправить.':'Не удалось выполнить действие.','error');}});
    await load();
  });
})();
